content = open("frontend/constants/colors.ts", "r", encoding="utf-8").read()
content = content.replace("#2D241E", "#F5F5DC")
content = content.replace("#FDFAF3", "#FDFBF7")
content = content.replace("#C8A84E", "#D4AF37")
content = content.replace("#E8D48A", "#EDD892")
content = content.replace("#A08030", "#8F7320")
content = content.replace("#1A1A1A", "#2D241E")
content = content.replace("#1A1A2E", "#FDFBF7")
open("frontend/constants/colors.ts", "w", encoding="utf-8").write(content)
print("DONE!")
